// Auto-generated by typst_inkscape.py from remarque-max-vraisemblance.svg
#let diagram(width: auto) = {
  // Original dimensions: 180.00pt x 90.00pt
  let W = 180.0000pt
  let H = 90.0000pt
  let s = if width == auto { 1.0 } else { width / W }

  stack(
    place(dx: s * 66.4521pt, dy: s * 19.0779pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$theta_1$])]),
    place(dx: s * 104.1853pt, dy: s * 23.3039pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$theta_2$])]),
    place(dx: s * 121.5561pt, dy: s * 39.0596pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$theta_3$])]),
    place(dx: s * 142.8815pt, dy: s * 60.0080pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x$])]),
    place(dx: s * 46.8497pt, dy: s * 14.0382pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$f_(theta) (x)$])]),
    image("remarque-max-vraisemblance_dobb_clean.svg", width: s * W),
  )
}
