// Auto-generated by typst_inkscape.py from visual-example-for-info-fisher.svg
#let diagram(width: auto) = {
  // Original dimensions: 180.00pt x 90.00pt
  let W = 180.0000pt
  let H = 90.0000pt
  let s = if width == auto { 1.0 } else { width / W }

  stack(
    place(dx: s * 23.5481pt, dy: s * 2.7755pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$log L(theta)$])]),
    place(dx: s * 46.8967pt, dy: s * 60.6480pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$hat(theta)$])]),
    place(dx: s * 115.5454pt, dy: s * 60.6480pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$theta$])]),
    image("visual-example-for-info-fisher_dobb_clean.svg", width: s * W),
  )
}