// Auto-generated by typst_inkscape.py from inverse-generalise.svg
#let diagram(width: auto) = {
  // Original dimensions: 180.00pt x 90.00pt
  let W = 180.0000pt
  let H = 90.0000pt
  let s = if width == auto { 1.0 } else { width / W }

  stack(
    place(dx: s * 114.5695pt, dy: s * 60.0071pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x$])]),
    place(dx: s * 19.7037pt, dy: s * 59.8788pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((1))$])]),
    place(dx: s * 27.6724pt, dy: s * 60.4742pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((2))$])]),
    place(dx: s * 38.5853pt, dy: s * 61.0740pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((3))$])]),
    place(dx: s * 55.9044pt, dy: s * 60.2768pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((4))$])]),
    place(dx: s * 77.2203pt, dy: s * 60.4809pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((5))$])]),
    place(dx: s * 22.7499pt, dy: s * 29.1174pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$alpha$])]),
    place(dx: s * 75.8329pt, dy: s * 47.0779pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$F^(-1) (alpha) = x_((4))$])]),
    image("inverse-generalise_dobb_clean.svg", width: s * W),
  )
}