// Auto-generated by typst_inkscape.py from huy-pizda.svg
#let diagram(width: auto) = {
  // Original dimensions: 180.00pt x 90.00pt
  let W = 180.0000pt
  let H = 90.0000pt
  let s = if width == auto { 1.0 } else { width / W }

  stack(
    image("huy-pizda_dobb_clean.svg", width: s * W),
  )
}