// Auto-generated by typst_inkscape.py from repr-graphique-repartition-empirique.svg
#let diagram(width: auto) = {
  // Original dimensions: 180.00pt x 90.00pt
  let W = 180.0000pt
  let H = 90.0000pt
  let s = if width == auto { 1.0 } else { width / W }

  stack(
    place(dx: s * 30.5327pt, dy: s * 3.7733pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$hat(F)_n(x)$])]),
    place(dx: s * 115.5854pt, dy: s * 60.5625pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x$])]),
    place(dx: s * 20.7196pt, dy: s * 60.4342pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((1))$])]),
    place(dx: s * 28.6883pt, dy: s * 61.0295pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((2))$])]),
    place(dx: s * 39.6012pt, dy: s * 61.6293pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((3))$])]),
    place(dx: s * 56.9203pt, dy: s * 60.8322pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((4))$])]),
    place(dx: s * 78.2362pt, dy: s * 61.0363pt, align(horizon + left)[  #block(text(size: s * 4.7625pt)[$x_((5))$])]),
    image("repr-graphique-repartition-empirique_dobb_clean.svg", width: s * W),
  )
}